site_name: Documentação UnB&Fit
repo_url: https://github.com/FGA0138-MDS-Ajax/2025.2-Ra
repo_name: GitHub/UnB&Fit
site_description: Documentação do projeto UnB&Fit
site_author: Equipe UnB&Fit

nav:
  - Home: index.md
  - Documento de visão:
    - Visão Geral do Produto: visao/visao_geral_prod.md
    - Visão Geral do Projeto: visao/visao_geral_proj.md
    - Processo de Desenvolvimento: visao/processo_desenv.md
    - Escopo do Projeto: visao/escopo_projeto.md
    - Métricas e Medições: visao/metricas_medicoes.md
    - Testes de Software: visao/testes.md
    - Referências: visao/ref.md

  - Atas de reuniões:
    - Concepção de produto e ideias: atas/ata1.md
    - Definições de papéis: atas/ata2.md
    - Lean inception: atas/ata3.md
    - Prototipação + documentação: atas/ata4.md

  - Arquitetura:
    - Introdução: arquitetura/introducao.md
    - Representação Arquitetural: arquitetura/representacao_arquitetural.md
    - Referências: arquitetura/ref.md

  - Guia de Contribuição: CONTRIBUTING.md


theme:
  name: material
  language: pt-BR
  palette:
    
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: blue
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.footer
  logo: assets/logo.png
  favicon: assets/favicon.ico
  
markdown_extensions:
  - toc:
      title: Sumário


plugins:
  - search
  - macros

extra_css:
  - assets/css/home.css
  - assets/css/global.css

extra:
  team:
  - name: Gabriel Alves
    username: CODEbugging3000
  - name: Rodrigo Àtila
    username: Rodrigoatila09
  - name: Yan Rodrigues
    username: yanrdgs-dev
  - name: Gabriel Mota
    username: LasagnaIsLove
  - name: Matheus Pinheiro
    username: matheus-06
  - name: Ângelo Cordova
    username: angeloldev
  - name: Giovana Martins de Brito
    username: Giih-martins
  - name: Guilherme Mendes
    username: Guilherme-Reis-Mendes
  - name: Samuel Leite
    username: osamuelleite
  - name: Pedro Inácio Santos
    username: pedrossantoss
  copyright: Copyright &copy; 2025 UnB&Fit
  version: 1.0.0
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FGA0138-MDS-Ajax/2025.2-Ra
    - icon: fontawesome/solid/envelope
      link: mailto:241025523@aluno.unb.br
  